@GroceryStore_HostAddress = https://localhost:7242

GET {{GroceryStore_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{GroceryStore_HostAddress}}/Items
Content-Type: application/json

{
    "name": "Chewing Gum",
    "price": "0.5",
    "comanyName": "Nova",
    "supplierName": "nova",
    "dateOfPurchase": "2025-04-15T00:00:00"
}
###



GET {{GroceryStore_HostAddress}}/Items

###
